varlists = [
    # ["AK8Gen_HiggsJet_MaxPt_Pt","gen_leading_Higgs_Pt"],
    # ["AK8Gen_HiggsJet_MaxPt_Eta","gen_leading_Higgs_Eta"],
    # ["AK8Gen_HiggsJet_MaxPt_Phi","gen_leading_Higgs_Phi"],
    # ["AK8Gen_HiggsJet_MaxPt_M","gen_leading_Higgs_M"],
    # ["AK8Gen_HiggsJet_minDMass_Pt","gen_leading_Higgs_Pt"],
    # ["AK8Gen_HiggsJet_minDMass_Eta","gen_leading_Higgs_Eta"],
    # ["AK8Gen_HiggsJet_minDMass_Phi","gen_leading_Higgs_Phi"],
    # ["AK8Gen_HiggsJet_minDMass_M","gen_leading_Higgs_M"],

    # ['AK8Gen_MergedWjets_MaxPt_Higgs_Pt','gen_leading_Higgs_Pt'],
    # ['AK8Gen_MergedWjets_MaxPt_Higgs_Eta','gen_leading_Higgs_Eta'],
    # ['AK8Gen_MergedWjets_MaxPt_Higgs_Phi','gen_leading_Higgs_Phi'],
    # ['AK8Gen_MergedWjets_MaxPt_Higgs_M','gen_leading_Higgs_M'],
    #
    ["AK8Gen_HiggsJet_minDMass_Pt","gen_leading_Higgs_Pt"],
    ["AK8Gen_HiggsJet_minDMass_Eta","gen_leading_Higgs_Eta"],
    ["AK8Gen_HiggsJet_minDMass_Phi","gen_leading_Higgs_Phi"],
    ["AK8Gen_HiggsJet_minDMass_M","gen_leading_Higgs_M"],
    # ["AK8Gen_HiggsJet_MaxPt_Pt","gen_leading_Higgs_Pt"],
    # ["AK8Gen_HiggsJet_MaxPt_Eta","gen_leading_Higgs_Eta"],
    # ["AK8Gen_HiggsJet_MaxPt_Phi","gen_leading_Higgs_Phi"],
    # ["AK8Gen_HiggsJet_MaxPt_M","gen_leading_Higgs_M"],
    # ['AK4GEN_AllResolved_Higgs_Pt','gen_leading_Higgs_Pt'],
    # ['AK4GEN_AllResolved_Higgs_Eta','gen_leading_Higgs_Eta'],
    # ['AK4GEN_AllResolved_Higgs_Phi','gen_leading_Higgs_Phi'],
    # ['AK4GEN_AllResolved_Higgs_M','gen_leading_Higgs_M'],
    # ['AK4GEN_AllResolved_onShellWboson_Pt','gen_leading_WBoson_Pt'],
    # ['AK4GEN_AllResolved_onShellWboson_Eta','gen_leading_WBoson_Eta'],
    # ['AK4GEN_AllResolved_onShellWboson_Phi','gen_leading_WBoson_Phi'],
    # ['AK4GEN_AllResolved_onShellWboson_M','gen_leading_WBoson_M'],
    # ['AK4GEN_AllResolved_offShellWboson_Pt','gen_Subleading_WBoson_Pt'],
    # ['AK4GEN_AllResolved_offShellWboson_Eta','gen_Subleading_WBoson_Eta'],
    # ['AK4GEN_AllResolved_offShellWboson_Phi','gen_Subleading_WBoson_Phi'],
    # ['AK4GEN_AllResolved_offShellWboson_M','gen_Subleading_WBoson_M'],
    #
    # ['OneAK8TwoAK4_minMass_ReconsH_M','gen_leading_Higgs_M'],
    # ['OneAK8TwoAK4_minMass_ReconsH_Pt','gen_leading_Higgs_Pt'],
    # ['OneAK8TwoAK4_minMass_ReconsH_Eta','gen_leading_Higgs_Eta'],
    # ['OneAK8TwoAK4_minMass_AK8_Pt','gen_leading_WBoson_Pt'],
    # ['OneAK8TwoAK4_minMass_AK8_Eta','gen_leading_WBoson_Eta'],
    # ['OneAK8TwoAK4_minMass_AK8_Pt','gen_Subleading_WBoson_Pt'],
    # ['OneAK8TwoAK4_minMass_AK8_Eta','gen_Subleading_WBoson_Eta'],
    # ['OneAK8TwoAK4_minMass_ReconsW_AK4_Pt','gen_leading_WBoson_Pt'],
    # ['OneAK8TwoAK4_minMass_ReconsW_AK4_Eta','gen_leading_WBoson_Eta'],
    # ['OneAK8TwoAK4_minMass_ReconsW_AK4_Pt','gen_Subleading_WBoson_Pt'],
    # ['OneAK8TwoAK4_minMass_ReconsW_AK4_Eta','gen_Subleading_WBoson_Eta'],

    # ['OneAK8TwoAK4_pTMax_ReconsH_M','gen_leading_Higgs_M'],
    # ['OneAK8TwoAK4_pTMax_ReconsH_Pt','gen_leading_Higgs_Pt'],
    # ['OneAK8TwoAK4_pTMax_ReconsH_Eta','gen_leading_Higgs_Eta'],
    # ['OneAK8TwoAK4_pTMax_AK8_Pt','gen_leading_WBoson_Pt'],
    # ['OneAK8TwoAK4_pTMax_AK8_Eta','gen_leading_WBoson_Eta'],
    # ['OneAK8TwoAK4_pTMax_AK8_Pt','gen_Subleading_WBoson_Pt'],
    # ['OneAK8TwoAK4_pTMax_AK8_Eta','gen_Subleading_WBoson_Eta'],
    # ['OneAK8TwoAK4_pTMax_ReconsW_AK4_Pt','gen_leading_WBoson_Pt'],
    # ['OneAK8TwoAK4_pTMax_ReconsW_AK4_Eta','gen_leading_WBoson_Eta'],
    # ['OneAK8TwoAK4_pTMax_ReconsW_AK4_Pt','gen_Subleading_WBoson_Pt'],
    # ['OneAK8TwoAK4_pTMax_ReconsW_AK4_Eta','gen_Subleading_WBoson_Eta'],
]