variables =  [
['gen_leading_photon_Pt', 'gen_Subleading_photon_Pt'],
['gen_leading_photon_Eta', 'gen_Subleading_photon_Eta'],
['gen_leading_photon_Phi', 'gen_Subleading_photon_Phi'],
['gen_leading_photon_M', 'gen_Subleading_photon_M'],
['gen_leading_WpJets_Pt', 'gen_Subleading_WpJets_Pt'],
['gen_leading_WpJets_Eta', 'gen_Subleading_WpJets_Eta'],
['gen_leading_WpJets_Phi', 'gen_Subleading_WpJets_Phi'],
['gen_leading_WpJets_M', 'gen_Subleading_WpJets_M'],
['gen_leading_WmJets_Pt', 'gen_Subleading_WmJets_Pt'],
['gen_leading_WmJets_Eta', 'gen_Subleading_WmJets_Eta'],
['gen_leading_WmJets_Phi', 'gen_Subleading_WmJets_Phi'],
['gen_leading_WmJets_M', 'gen_Subleading_WmJets_M'],
['gen_leading_WBoson_Pt', 'gen_Subleading_WBoson_Pt'],
['gen_leading_WBoson_Eta', 'gen_Subleading_WBoson_Eta'],
['gen_leading_WBoson_Phi', 'gen_Subleading_WBoson_Phi'],
['gen_leading_WBoson_M', 'gen_Subleading_WBoson_M'],
['gen_leading_Higgs_Pt', 'gen_Subleading_Higgs_Pt'],
['gen_leading_Higgs_Eta', 'gen_Subleading_Higgs_Eta'],
['gen_leading_Higgs_Phi', 'gen_Subleading_Higgs_Phi'],
['gen_leading_Higgs_M', 'gen_Subleading_Higgs_M'],
['gen_deltaR_Photon0_Photon1', 'gen_deltaR_Photon0_WmJ0', 'gen_deltaR_Photon0_WmJ1', 'gen_deltaR_Photon0_WpJ0', 'gen_deltaR_Photon0_WpJ1'],
['gen_deltaR_Photon1_WmJ0', 'gen_deltaR_Photon1_WmJ1', 'gen_deltaR_Photon1_WpJ0', 'gen_deltaR_Photon1_WpJ1'],
['gen_deltaR_Wp_Wm', 'gen_deltaR_H1_H2'],
['gen_deltaR_WpJ0_WpJ1', 'gen_deltaR_WpJ0_WmJ0', 'gen_deltaR_WpJ0_WmJ1', 'gen_deltaR_WpJ1_WmJ0', 'gen_deltaR_WpJ1_WmJ1', 'gen_deltaR_WmJ0_WmJ1'],
]
