variables =  {
'gen_leading_photon_Pt':['gen_leading_photon_Pt', 'Leading Photon p_{T}', '', 25, 0, 500],
'gen_leading_photon_Eta':['gen_leading_photon_Eta', 'Leading Photon #eta', '', 25, -5., 5.],
'gen_leading_photon_Phi':['gen_leading_photon_Phi', 'Leading Photon #phi', '', 25, -3.5, 3.5],
'gen_leading_photon_M':['gen_leading_photon_M', 'Leading Photon mass', '', 25, -0.00005, 0.00005],
'gen_Subleading_photon_Pt':['gen_Subleading_photon_Pt', 'Sub-Leading Photon p_{T}', '', 25, 0, 500],
'gen_Subleading_photon_Eta':['gen_Subleading_photon_Eta', 'Sub-Leading Photon #eta', '', 25, -5, 5],
'gen_Subleading_photon_Phi':['gen_Subleading_photon_Phi', 'Sub-Leading Photon #phi', '', 25, -3.5, 3.5],
'gen_Subleading_photon_M':['gen_Subleading_photon_M', 'Sub-Leading Photon mass', '', 25, -0.00003, 0.00003],
'gen_leading_WpJets_Pt':['gen_leading_WpJets_Pt', 'W1 Leading jet p_{T}', '', 25, 0, 250],
'gen_leading_WpJets_Eta':['gen_leading_WpJets_Eta', 'W1 Leading jet #eta', '', 25, -5., 5.],
'gen_leading_WpJets_Phi':['gen_leading_WpJets_Phi', 'W1 Leading jet #phi', '', 25, -3.5, 3.5],
'gen_leading_WpJets_M':['gen_leading_WpJets_M', 'W1 Leading jet mass', '', 25, 0, 1.7],
'gen_Subleading_WpJets_Pt':['gen_Subleading_WpJets_Pt', 'W1 Sub-Leading jet p_{T}', '', 25, 0, 250],
'gen_Subleading_WpJets_Eta':['gen_Subleading_WpJets_Eta', 'W1 Sub-Leading jet #eta', '', 25, -5., 5.],
'gen_Subleading_WpJets_Phi':['gen_Subleading_WpJets_Phi', 'W1 Sub-Leading jet #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WpJets_M':['gen_Subleading_WpJets_M', 'W1 Sub-Leading jet mass', '', 25, 0, 1.7],
'gen_leading_WmJets_Pt':['gen_leading_WmJets_Pt', 'W2 Leading jet p_{T}', '', 25, 0, 250],
'gen_leading_WmJets_Eta':['gen_leading_WmJets_Eta', 'W2 Leading jet #eta', '', 25, -5., 5.],
'gen_leading_WmJets_Phi':['gen_leading_WmJets_Phi', 'W2 Leading jet #phi', '', 25, -3.5, 3.5],
'gen_leading_WmJets_M':['gen_leading_WmJets_M', 'W2 Leading jet mass', '', 25, 0, 1.7],
'gen_Subleading_WmJets_Pt':['gen_Subleading_WmJets_Pt', 'W2 Sub-Leading jet p_{T}', '', 25, 0, 250],
'gen_Subleading_WmJets_Eta':['gen_Subleading_WmJets_Eta', 'W2 Sub-Leading jet #eta', '', 25, -5., 5.],
'gen_Subleading_WmJets_Phi':['gen_Subleading_WmJets_Phi', 'W2 Sub-Leading jet #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WmJets_M':['gen_Subleading_WmJets_M', 'W2 Sub-Leading jet mass', '', 25, 0, 1.7],
'gen_leading_WBoson_Pt':['gen_leading_WBoson_Pt', 'Leading W-boson p_{T}', '', 25, 0, 500],
'gen_leading_WBoson_Eta':['gen_leading_WBoson_Eta', 'Leading W-boson #eta', '', 25, -5., 5.],
'gen_leading_WBoson_Phi':['gen_leading_WBoson_Phi', 'Leading W-boson #phi', '', 25, -3.5, 3.5],
'gen_leading_WBoson_M':['gen_leading_WBoson_M', 'Leading W-boson mass', '', 25, 0, 100],
'gen_Subleading_WBoson_Pt':['gen_Subleading_WBoson_Pt', 'Sub-Leading W-boson p_{T}', '', 25, 0, 500],
'gen_Subleading_WBoson_Eta':['gen_Subleading_WBoson_Eta', 'Sub-Leading W-boson #eta', '', 25, -5., 5.],
'gen_Subleading_WBoson_Phi':['gen_Subleading_WBoson_Phi', 'Sub-Leading W-boson #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WBoson_M':['gen_Subleading_WBoson_M', 'Sub-Leading W-boson mass', '', 25, 0, 100],
'gen_leading_Higgs_Pt':['gen_leading_Higgs_Pt', 'Leading Higgs p_{T}', '', 25, 0, 500],
'gen_leading_Higgs_Eta':['gen_leading_Higgs_Eta', 'Leading Higgs #eta', '', 25, -5., 5.],
'gen_leading_Higgs_Phi':['gen_leading_Higgs_Phi', 'Leading Higgs #phi', '', 25, -3.5, 3.5],
'gen_leading_Higgs_M':['gen_leading_Higgs_M', 'Leading Higgs mass', '', 25, 100, 130],
'gen_Subleading_Higgs_Pt':['gen_Subleading_Higgs_Pt', 'Sub-Leading Higgs p_{T}', '', 25, 0, 500],
'gen_Subleading_Higgs_Eta':['gen_Subleading_Higgs_Eta', 'Sub-Leading Higgs #eta', '', 25, -5., 5.],
'gen_Subleading_Higgs_Phi':['gen_Subleading_Higgs_Phi', 'Sub-Leading Higgs #phi', '', 25, -3.5, 3.5],
'gen_Subleading_Higgs_M':['gen_Subleading_Higgs_M', 'Sub-Leading Higgs mass', '', 25, 100, 130],
'gen_deltaR_Photon0_Photon1':['gen_deltaR_Photon0_Photon1', '#Delta R(#gamma 0, #gamma 1)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WmJ0':['gen_deltaR_Photon0_WmJ0', '#Delta R(#gamma 0, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WmJ1':['gen_deltaR_Photon0_WmJ1', '#Delta R(#gamma 0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WpJ0':['gen_deltaR_Photon0_WpJ0', '#Delta R(#gamma 0, W1-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WpJ1':['gen_deltaR_Photon0_WpJ1', '#Delta R(#gamma 0, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WmJ0':['gen_deltaR_Photon1_WmJ0', '#Delta R(#gamma 1, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WmJ1':['gen_deltaR_Photon1_WmJ1', '#Delta R(#gamma 1, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WpJ0':['gen_deltaR_Photon1_WpJ0', '#Delta R(#gamma 1, W1-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WpJ1':['gen_deltaR_Photon1_WpJ1', '#Delta R(#gamma 1, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WpJ1':['gen_deltaR_WpJ0_WpJ1', '#Delta R(W1-J0, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WmJ0':['gen_deltaR_WpJ0_WmJ0', '#Delta R(W1-J0, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WmJ1':['gen_deltaR_WpJ0_WmJ1', '#Delta R(W1-J0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ1_WmJ0':['gen_deltaR_WpJ1_WmJ0', '#Delta R(W1-J1, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_WpJ1_WmJ1':['gen_deltaR_WpJ1_WmJ1', '#Delta R(W1-J1, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_WmJ0_WmJ1':['gen_deltaR_WmJ0_WmJ1', '#Delta R(W2-J0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Wp_Wm':['gen_deltaR_Wp_Wm', '#Delta R(W1, W2)', '', 25, 0, 4.5],
'gen_deltaR_H1_H2':['gen_deltaR_H1_H2', '#Delta R(H1, H2)', '', 25, 0, 4.5],
}
