variables =  {
'gen_leading_photon_Pt':['gen_leading_photon_Pt', 'Leading Photon p_{T}', '', 25, 0, 500],
'gen_leading_photon_Eta':['gen_leading_photon_Eta', 'Leading Photon #eta', '', 25, -5., 5.],
'gen_leading_photon_Phi':['gen_leading_photon_Phi', 'Leading Photon #phi', '', 25, -3.5, 3.5],
'gen_leading_photon_M':['gen_leading_photon_M', 'Leading Photon mass', '', 25, -0.00005, 0.00005],
'gen_Subleading_photon_Pt':['gen_Subleading_photon_Pt', 'Sub-Leading Photon p_{T}', '', 25, 0, 500],
'gen_Subleading_photon_Eta':['gen_Subleading_photon_Eta', 'Sub-Leading Photon #eta', '', 25, -5, 5],
'gen_Subleading_photon_Phi':['gen_Subleading_photon_Phi', 'Sub-Leading Photon #phi', '', 25, -3.5, 3.5],
'gen_Subleading_photon_M':['gen_Subleading_photon_M', 'Sub-Leading Photon mass', '', 25, -0.00003, 0.00003],
'gen_leading_WpJets_Pt':['gen_leading_WpJets_Pt', 'W1 Leading jet p_{T}', '', 25, 0, 250],
'gen_leading_WpJets_Eta':['gen_leading_WpJets_Eta', 'W1 Leading jet #eta', '', 25, -5., 5.],
'gen_leading_WpJets_Phi':['gen_leading_WpJets_Phi', 'W1 Leading jet #phi', '', 25, -3.5, 3.5],
'gen_leading_WpJets_M':['gen_leading_WpJets_M', 'W1 Leading jet mass', '', 25, 0, 1.7],
'gen_Subleading_WpJets_Pt':['gen_Subleading_WpJets_Pt', 'W1 Sub-Leading jet p_{T}', '', 25, 0, 250],
'gen_Subleading_WpJets_Eta':['gen_Subleading_WpJets_Eta', 'W1 Sub-Leading jet #eta', '', 25, -5., 5.],
'gen_Subleading_WpJets_Phi':['gen_Subleading_WpJets_Phi', 'W1 Sub-Leading jet #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WpJets_M':['gen_Subleading_WpJets_M', 'W1 Sub-Leading jet mass', '', 25, 0, 1.7],
'gen_leading_WmJets_Pt':['gen_leading_WmJets_Pt', 'W2 Leading jet p_{T}', '', 25, 0, 250],
'gen_leading_WmJets_Eta':['gen_leading_WmJets_Eta', 'W2 Leading jet #eta', '', 25, -5., 5.],
'gen_leading_WmJets_Phi':['gen_leading_WmJets_Phi', 'W2 Leading jet #phi', '', 25, -3.5, 3.5],
'gen_leading_WmJets_M':['gen_leading_WmJets_M', 'W2 Leading jet mass', '', 25, 0, 1.7],
'gen_Subleading_WmJets_Pt':['gen_Subleading_WmJets_Pt', 'W2 Sub-Leading jet p_{T}', '', 25, 0, 250],
'gen_Subleading_WmJets_Eta':['gen_Subleading_WmJets_Eta', 'W2 Sub-Leading jet #eta', '', 25, -5., 5.],
'gen_Subleading_WmJets_Phi':['gen_Subleading_WmJets_Phi', 'W2 Sub-Leading jet #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WmJets_M':['gen_Subleading_WmJets_M', 'W2 Sub-Leading jet mass', '', 25, 0, 1.7],
'gen_leading_WBoson_Pt':['gen_leading_WBoson_Pt', 'Leading W-boson p_{T}', '', 25, 0, 500],
'gen_leading_WBoson_Eta':['gen_leading_WBoson_Eta', 'Leading W-boson #eta', '', 25, -5., 5.],
'gen_leading_WBoson_Phi':['gen_leading_WBoson_Phi', 'Leading W-boson #phi', '', 25, -3.5, 3.5],
'gen_leading_WBoson_M':['gen_leading_WBoson_M', 'Leading W-boson mass', '', 25, 0, 100],
'gen_Subleading_WBoson_Pt':['gen_Subleading_WBoson_Pt', 'Sub-Leading W-boson p_{T}', '', 25, 0, 500],
'gen_Subleading_WBoson_Eta':['gen_Subleading_WBoson_Eta', 'Sub-Leading W-boson #eta', '', 25, -5., 5.],
'gen_Subleading_WBoson_Phi':['gen_Subleading_WBoson_Phi', 'Sub-Leading W-boson #phi', '', 25, -3.5, 3.5],
'gen_Subleading_WBoson_M':['gen_Subleading_WBoson_M', 'Sub-Leading W-boson mass', '', 25, 0, 100],
'gen_leading_Higgs_Pt':['gen_leading_Higgs_Pt', 'Leading Higgs p_{T}', '', 25, 0, 500],
'gen_leading_Higgs_Eta':['gen_leading_Higgs_Eta', 'Leading Higgs #eta', '', 25, -5., 5.],
'gen_leading_Higgs_Phi':['gen_leading_Higgs_Phi', 'Leading Higgs #phi', '', 25, -3.5, 3.5],
'gen_leading_Higgs_M':['gen_leading_Higgs_M', 'Leading Higgs mass', '', 25, 100, 130],
'gen_Subleading_Higgs_Pt':['gen_Subleading_Higgs_Pt', 'Sub-Leading Higgs p_{T}', '', 25, 0, 500],
'gen_Subleading_Higgs_Eta':['gen_Subleading_Higgs_Eta', 'Sub-Leading Higgs #eta', '', 25, -5., 5.],
'gen_Subleading_Higgs_Phi':['gen_Subleading_Higgs_Phi', 'Sub-Leading Higgs #phi', '', 25, -3.5, 3.5],
'gen_Subleading_Higgs_M':['gen_Subleading_Higgs_M', 'Sub-Leading Higgs mass', '', 25, 100, 130],
'gen_deltaR_Photon0_Photon1':['gen_deltaR_Photon0_Photon1', '#Delta R(#gamma 0, #gamma 1)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WmJ0':['gen_deltaR_Photon0_WmJ0', '#Delta R(#gamma 0, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WmJ1':['gen_deltaR_Photon0_WmJ1', '#Delta R(#gamma 0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WpJ0':['gen_deltaR_Photon0_WpJ0', '#Delta R(#gamma 0, W1-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon0_WpJ1':['gen_deltaR_Photon0_WpJ1', '#Delta R(#gamma 0, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WmJ0':['gen_deltaR_Photon1_WmJ0', '#Delta R(#gamma 1, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WmJ1':['gen_deltaR_Photon1_WmJ1', '#Delta R(#gamma 1, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WpJ0':['gen_deltaR_Photon1_WpJ0', '#Delta R(#gamma 1, W1-J0)', '', 25, 0, 4.5],
'gen_deltaR_Photon1_WpJ1':['gen_deltaR_Photon1_WpJ1', '#Delta R(#gamma 1, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WpJ1':['gen_deltaR_WpJ0_WpJ1', '#Delta R(W1-J0, W1-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WmJ0':['gen_deltaR_WpJ0_WmJ0', '#Delta R(W1-J0, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_WpJ0_WmJ1':['gen_deltaR_WpJ0_WmJ1', '#Delta R(W1-J0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_WpJ1_WmJ0':['gen_deltaR_WpJ1_WmJ0', '#Delta R(W1-J1, W2-J0)', '', 25, 0, 4.5],
'gen_deltaR_WpJ1_WmJ1':['gen_deltaR_WpJ1_WmJ1', '#Delta R(W1-J1, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_WmJ0_WmJ1':['gen_deltaR_WmJ0_WmJ1', '#Delta R(W2-J0, W2-J1)', '', 25, 0, 4.5],
'gen_deltaR_Wp_Wm':['gen_deltaR_Wp_Wm', '#Delta R(W1, W2)', '', 25, 0, 4.5],
'gen_deltaR_H1_H2':['gen_deltaR_H1_H2', '#Delta R(H1, H2)', '', 25, 0, 4.5],


'genJetAK4_njets':['genJetAK4_njets', 'number of cleaned AK4 jets', '', 35, 0, 35],
# 'genJetAK4_leading_Pt':['genJetAK4_leading_Pt', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_leading_Eta':['genJetAK4_leading_Eta', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_leading_Phi':['genJetAK4_leading_Phi', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_leading_M':['genJetAK4_leading_M', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_leading_Energy':['genJetAK4_leading_Energy', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_Subleading_Pt':['genJetAK4_Subleading_Pt', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_Subleading_Eta':['genJetAK4_Subleading_Eta', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_Subleading_Phi':['genJetAK4_Subleading_Phi', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_Subleading_M':['genJetAK4_Subleading_M', 'AK4 OnShell Jet1', '', 25, ],
# 'genJetAK4_Subleading_Energy':['genJetAK4_Subleading_Energy', 'AK4 OnShell Jet1', '', 25, ],
'genJetAK8_njets':['genJetAK8_njets', 'Number of cleaned AK8 jets', '', 25, 0, 25.0],
'AK8Gen_HiggsJet_MaxPt_Pt':['AK8Gen_HiggsJet_MaxPt_Pt', 'AK8 Higgs Jet p_{T}', '', 25, 0, 500],
'AK8Gen_HiggsJet_MaxPt_Eta':['AK8Gen_HiggsJet_MaxPt_Eta', 'AK8 Higgs Jet #eta', '', 25, -5.0, 5.0],
'AK8Gen_HiggsJet_MaxPt_Phi':['AK8Gen_HiggsJet_MaxPt_Phi', 'AK8 Higgs Jet #phi', '', 25, -3.5, 3.5],
'AK8Gen_HiggsJet_MaxPt_M':['AK8Gen_HiggsJet_MaxPt_M', 'AK8 Higgs Jet mass', '', 25, 0, 200],
'AK8Gen_HiggsJet_MaxPt_deltaR_H1':['AK8Gen_HiggsJet_MaxPt_deltaR_H1', 'AK8 Higgs Jet #Delta R with Higgs PID', '', 25, 0, 7],
'AK8Gen_HiggsJet_MaxPt_deltaR_H2':['AK8Gen_HiggsJet_MaxPt_deltaR_H2', 'AK8 Higgs Jet #Delta R with Higgs PID', '', 25, 0, 7],
'AK8Gen_HiggsJet_minDMass_Pt':['AK8Gen_HiggsJet_minDMass_Pt', 'AK8 Higgs Jet p_{T}', '', 25, 0, 500],
'AK8Gen_HiggsJet_minDMass_Eta':['AK8Gen_HiggsJet_minDMass_Eta', 'AK8 Higgs Jet #eta', '', 25, -5.0, 5.0],
'AK8Gen_HiggsJet_minDMass_Phi':['AK8Gen_HiggsJet_minDMass_Phi', 'AK8 Higgs Jet #phi', '', 25, -3.5, 3.5],
'AK8Gen_HiggsJet_minDMass_M':['AK8Gen_HiggsJet_minDMass_M', 'AK8 Higgs Jet mass', '', 25, 0, 200],
'AK8Gen_HiggsJet_minDMass_deltaR_H1':['AK8Gen_HiggsJet_minDMass_deltaR_H1', 'AK8 Higgs Jet #Delta R with Higgs PID', '', 25, 0, 7],
'AK8Gen_HiggsJet_minDMass_deltaR_H2':['AK8Gen_HiggsJet_minDMass_deltaR_H2', 'AK8 Higgs Jet #Delta R with Higgs PID', '', 25, 0, 7],
'AK8Gen_MergedWjets_MaxPt_Leading_Pt':['AK8Gen_MergedWjets_MaxPt_Leading_Pt', 'AK8 Leading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_MaxPt_Leading_Eta':['AK8Gen_MergedWjets_MaxPt_Leading_Eta', 'AK8 Leading Wjet #eta', '', 25, -5.0, 5.0],
'AK8Gen_MergedWjets_MaxPt_Leading_Phi':['AK8Gen_MergedWjets_MaxPt_Leading_Phi', 'AK8 Leading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_MaxPt_Leading_M':['AK8Gen_MergedWjets_MaxPt_Leading_M', 'AK8 Leading Wjet Mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_MaxPt_Leading_deltaR_H1':['AK8Gen_MergedWjets_MaxPt_Leading_deltaR_H1', '#Delta R(AK8 Leading Wjet, Higgs1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_MaxPt_Leading_deltaR_H2':['AK8Gen_MergedWjets_MaxPt_Leading_deltaR_H2', '#Delta R(AK8 Leading Wjet, Higgs2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_MaxPt_SubLeading_Pt':['AK8Gen_MergedWjets_MaxPt_SubLeading_Pt', 'AK8 SubLeading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_MaxPt_SubLeading_Eta':['AK8Gen_MergedWjets_MaxPt_SubLeading_Eta', 'AK8 SubLeading Wjet #eta', '', 25, -5.0, 5.0],
'AK8Gen_MergedWjets_MaxPt_SubLeading_Phi':['AK8Gen_MergedWjets_MaxPt_SubLeading_Phi', 'AK8 SubLeading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_MaxPt_SubLeading_M':['AK8Gen_MergedWjets_MaxPt_SubLeading_M', 'AK8 SubLeading Wjet Mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_MaxPt_SubLeading_deltaR_H1':['AK8Gen_MergedWjets_MaxPt_SubLeading_deltaR_H1', '#Delta R(AK8 SubLeading Wjet, Higgs1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_MaxPt_SubLeading_deltaR_H2':['AK8Gen_MergedWjets_MaxPt_SubLeading_deltaR_H2', '#Delta R(AK8 SubLeading Wjet, Higgs2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_MaxPt_LeadingSubLeading_DR':['AK8Gen_MergedWjets_MaxPt_LeadingSubLeading_DR', '#Delta R(AK8 Leading Wjet, AK8 SubLeading Wjet)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minDMass_Leading_Pt':['AK8Gen_MergedWjets_minDMass_Leading_Pt', 'AK8 Leading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_minDMass_Leading_Eta':['AK8Gen_MergedWjets_minDMass_Leading_Eta', 'AK8 Leading Wjet #eta', '', 25, -5, 5],
'AK8Gen_MergedWjets_minDMass_Leading_Phi':['AK8Gen_MergedWjets_minDMass_Leading_Phi', 'AK8 Leading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_minDMass_Leading_M':['AK8Gen_MergedWjets_minDMass_Leading_M', 'AK8 Leading Wjet mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_minDMass_Leading_deltaR_H1':['AK8Gen_MergedWjets_minDMass_Leading_deltaR_H1', '#Delta R(AK8 Leading Wjet, H1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minDMass_Leading_deltaR_H2':['AK8Gen_MergedWjets_minDMass_Leading_deltaR_H2', '#Delta R(AK8 Leading Wjet, H2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minDMass_SubLeading_Pt':['AK8Gen_MergedWjets_minDMass_SubLeading_Pt', 'AK8 Leading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_minDMass_SubLeading_Eta':['AK8Gen_MergedWjets_minDMass_SubLeading_Eta', 'AK8 Leading Wjet #eta', '', 25, -5, 5],
'AK8Gen_MergedWjets_minDMass_SubLeading_Phi':['AK8Gen_MergedWjets_minDMass_SubLeading_Phi', 'AK8 Leading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_minDMass_SubLeading_M':['AK8Gen_MergedWjets_minDMass_SubLeading_M', 'AK8 Leading Wjet mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_minDMass_SubLeading_deltaR_H1':['AK8Gen_MergedWjets_minDMass_SubLeading_deltaR_H1', '#Delta R(AK8 Leading Wjet, H1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minDMass_SubLeading_deltaR_H2':['AK8Gen_MergedWjets_minDMass_SubLeading_deltaR_H2', '#Delta R(AK8 Leading Wjet, H2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minDMass_LeadingSubLeading_DR':['AK8Gen_MergedWjets_minDMass_LeadingSubLeading_DR', '#Delta R(AK8 Leading Wjet, AK8 SubLeading Wjet)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minWminHmass_Leading_Pt':['AK8Gen_MergedWjets_minWminHmass_Leading_Pt', 'AK8 Leading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_minWminHmass_Leading_Eta':['AK8Gen_MergedWjets_minWminHmass_Leading_Eta', 'AK8 Leading Wjet #eta', '', 25, -5, 5],
'AK8Gen_MergedWjets_minWminHmass_Leading_Phi':['AK8Gen_MergedWjets_minWminHmass_Leading_Phi', 'AK8 Leading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_minWminHmass_Leading_M':['AK8Gen_MergedWjets_minWminHmass_Leading_M', 'AK8 Leading Wjet mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_minWminHmass_Leading_deltaR_H1':['AK8Gen_MergedWjets_minWminHmass_Leading_deltaR_H1', '#Delta R(AK8 Leading Wjet, H1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minWminHmass_Leading_deltaR_H2':['AK8Gen_MergedWjets_minWminHmass_Leading_deltaR_H2', '#Delta R(AK8 Leading Wjet, H2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_Pt':['AK8Gen_MergedWjets_minWminHmass_SubLeading_Pt', 'AK8 SubLeading Wjet p_{T}', '', 25, 0, 500],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_Eta':['AK8Gen_MergedWjets_minWminHmass_SubLeading_Eta', 'AK8 SubLeading Wjet #eta', '', 25, -5, 5],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_Phi':['AK8Gen_MergedWjets_minWminHmass_SubLeading_Phi', 'AK8 SubLeading Wjet #phi', '', 25, -3.5, 3.5],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_M':['AK8Gen_MergedWjets_minWminHmass_SubLeading_M', 'AK8 SubLeading Wjet mass', '', 25, 0, 200],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_deltaR_H1':['AK8Gen_MergedWjets_minWminHmass_SubLeading_deltaR_H1', '#Delta R(AK8 SubLeading Wjet, H1 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minWminHmass_SubLeading_deltaR_H2':['AK8Gen_MergedWjets_minWminHmass_SubLeading_deltaR_H2', '#Delta R(AK8 SubLeading Wjet, H2 PID)', '', 25, 0, 7],
'AK8Gen_MergedWjets_minWminHmass_LeadingSubLeading_DR':['AK8Gen_MergedWjets_minWminHmass_LeadingSubLeading_DR', '#Delta R(AK8 Leading Wjet, AK8 SubLeading Wjet)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_Pt':['AK4GEN_AllResolved_onShellJet1_Pt', 'AK4 OnShell Jet1 p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_onShellJet1_Eta':['AK4GEN_AllResolved_onShellJet1_Eta', 'AK4 OnShell Jet1 #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_onShellJet1_Phi':['AK4GEN_AllResolved_onShellJet1_Phi', 'AK4 OnShell Jet1 #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_onShellJet1_M':['AK4GEN_AllResolved_onShellJet1_M', 'AK4 OnShell Jet1 mass', '', 25, 0, 200],
'AK4GEN_AllResolved_onShellJet1_dR_q1':['AK4GEN_AllResolved_onShellJet1_dR_q1', '#Delta R(AK4 OnShell Jet1, Quark1)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_dR_q2':['AK4GEN_AllResolved_onShellJet1_dR_q2', '#Delta R(AK4 OnShell Jet1, Quark2)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_dR_q3':['AK4GEN_AllResolved_onShellJet1_dR_q3', '#Delta R(AK4 OnShell Jet1, Quark3)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_dR_q4':['AK4GEN_AllResolved_onShellJet1_dR_q4', '#Delta R(AK4 OnShell Jet1, Quark4)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_dR_g1':['AK4GEN_AllResolved_onShellJet1_dR_g1', '#Delta R(AK4 OnShell Jet1, Photon1)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet1_dR_g2':['AK4GEN_AllResolved_onShellJet1_dR_g2', '#Delta R(AK4 OnShell Jet1, Photon2)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_Pt':['AK4GEN_AllResolved_onShellJet2_Pt', 'AK4 OnShell Jet2p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_onShellJet2_Eta':['AK4GEN_AllResolved_onShellJet2_Eta', 'AK4 OnShell Jet2 #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_onShellJet2_Phi':['AK4GEN_AllResolved_onShellJet2_Phi', 'AK4 OnShell Jet2 #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_onShellJet2_M':['AK4GEN_AllResolved_onShellJet2_M', 'AK4 OnShell Jet2 mass', '', 25, 0, 500],
'AK4GEN_AllResolved_onShellJets_dR':['AK4GEN_AllResolved_onShellJets_dR', '#Delta R(AK4 OnShell Jet1, Jet2)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_q1':['AK4GEN_AllResolved_onShellJet2_dR_q1', '#Delta R(AK4 OnShell Jet1, Quark1)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_q2':['AK4GEN_AllResolved_onShellJet2_dR_q2', '#Delta R(AK4 OnShell Jet1, Quark2)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_q3':['AK4GEN_AllResolved_onShellJet2_dR_q3', '#Delta R(AK4 OnShell Jet1, Quark3)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_q4':['AK4GEN_AllResolved_onShellJet2_dR_q4', '#Delta R(AK4 OnShell Jet1, Quark4)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_g1':['AK4GEN_AllResolved_onShellJet2_dR_g1', '#Delta R(AK4 OnShell Jet1, Photon1)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellJet2_dR_g2':['AK4GEN_AllResolved_onShellJet2_dR_g2', '#Delta R(AK4 OnShell Jet1, Photon2)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_Pt':['AK4GEN_AllResolved_offShellJet1_Pt', 'AK4 OffShell Jet1 p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellJet1_Eta':['AK4GEN_AllResolved_offShellJet1_Eta', 'AK4 OffShell Jet1  #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_offShellJet1_Phi':['AK4GEN_AllResolved_offShellJet1_Phi', 'AK4 OffShell Jet1  #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_offShellJet1_M':['AK4GEN_AllResolved_offShellJet1_M', 'AK4 OffShell Jet1  mass', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellJet1_dR_q1':['AK4GEN_AllResolved_offShellJet1_dR_q1', '#Delta R(AK4 OffShell Jet1, Quark1)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_dR_q2':['AK4GEN_AllResolved_offShellJet1_dR_q2', '#Delta R(AK4 OffShell Jet1, Quark2)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_dR_q3':['AK4GEN_AllResolved_offShellJet1_dR_q3', '#Delta R(AK4 OffShell Jet1, Quark3)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_dR_q4':['AK4GEN_AllResolved_offShellJet1_dR_q4', '#Delta R(AK4 OffShell Jet1, Quark4)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_dR_g1':['AK4GEN_AllResolved_offShellJet1_dR_g1', '#Delta R(AK4 OffShell Jet1, Photon1)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet1_dR_g2':['AK4GEN_AllResolved_offShellJet1_dR_g2', '#Delta R(AK4 OffShell Jet1, Photon2)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_Pt':['AK4GEN_AllResolved_offShellJet2_Pt', 'AK4 OffShell Jet2 p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellJet2_Eta':['AK4GEN_AllResolved_offShellJet2_Eta', 'AK4 OffShell Jet2  #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_offShellJet2_Phi':['AK4GEN_AllResolved_offShellJet2_Phi', 'AK4 OffShell Jet2  #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_offShellJet2_M':['AK4GEN_AllResolved_offShellJet2_M', 'AK4 OffShell Jet2  mass', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellJets_dR':['AK4GEN_AllResolved_offShellJets_dR', '#Delta R(AK4 OffShell Wjet, AK4OnShell Wjet)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShelloffShellJets_dR':['AK4GEN_AllResolved_onShelloffShellJets_dR', 'AK4 #DeltaR(OnShell W, OffShell W)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_q1':['AK4GEN_AllResolved_offShellJet2_dR_q1', '#Delta R(AK4 OffShell Jet2, Quark1)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_q2':['AK4GEN_AllResolved_offShellJet2_dR_q2', '#Delta R(AK4 OffShell Jet2, Quark2)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_q3':['AK4GEN_AllResolved_offShellJet2_dR_q3', '#Delta R(AK4 OffShell Jet2, Quark3)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_q4':['AK4GEN_AllResolved_offShellJet2_dR_q4', '#Delta R(AK4 OffShell Jet2, Quark4)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_g1':['AK4GEN_AllResolved_offShellJet2_dR_g1', '#Delta R(AK4 OffShell Jet2, Photon1)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellJet2_dR_g2':['AK4GEN_AllResolved_offShellJet2_dR_g2', '#Delta R(AK4 OffShell Jet2, Photon2)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellWboson_Pt':['AK4GEN_AllResolved_onShellWboson_Pt', 'AK4 OnShell W p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_onShellWboson_Eta':['AK4GEN_AllResolved_onShellWboson_Eta', 'AK4 OnShell W  #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_onShellWboson_Phi':['AK4GEN_AllResolved_onShellWboson_Phi', 'AK4 OnShell W  #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_onShellWboson_M':['AK4GEN_AllResolved_onShellWboson_M', 'AK4 OnShell W  mass', '', 25, 0, 500],
'AK4GEN_AllResolved_onShellWboson_dR_W0PID':['AK4GEN_AllResolved_onShellWboson_dR_W0PID', '#Delta R(AK4 OnShell W, W1 PID)', '', 25, 0, 7],
'AK4GEN_AllResolved_onShellWboson_dR_W1PID':['AK4GEN_AllResolved_onShellWboson_dR_W1PID', '#Delta R(AK4 OnShell W, W2 PID)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellWboson_Pt':['AK4GEN_AllResolved_offShellWboson_Pt', 'AK4 OnShell W p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellWboson_Eta':['AK4GEN_AllResolved_offShellWboson_Eta', 'AK4 OnShell W  #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_offShellWboson_Phi':['AK4GEN_AllResolved_offShellWboson_Phi', 'AK4 OnShell W  #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_offShellWboson_M':['AK4GEN_AllResolved_offShellWboson_M', 'AK4 OnShell W  mass', '', 25, 0, 500],
'AK4GEN_AllResolved_offShellWboson_dR_W0PID':['AK4GEN_AllResolved_offShellWboson_dR_W0PID', '#Delta R(AK4 OffShell W, W1 PID)', '', 25, 0, 7],
'AK4GEN_AllResolved_offShellWboson_dR_W1PID':['AK4GEN_AllResolved_offShellWboson_dR_W1PID', '#Delta R(AK4 OffShell W, W2 PID)', '', 25, 0, 7],
'AK4GEN_AllResolved_Higgs_Pt':['AK4GEN_AllResolved_Higgs_Pt', 'AK4 Higgs jet p_{T}', '', 25, 0, 500],
'AK4GEN_AllResolved_Higgs_Eta':['AK4GEN_AllResolved_Higgs_Eta', 'AK4 Higgs jet #eta', '', 25, -5, 5],
'AK4GEN_AllResolved_Higgs_Phi':['AK4GEN_AllResolved_Higgs_Phi', 'AK4 Higgs jet #phi', '', 25, -3.5, 3.5],
'AK4GEN_AllResolved_Higgs_M':['AK4GEN_AllResolved_Higgs_M', 'AK4 Higgs jet M', '', 25, 0, 500],
'AK4GEN_AllResolved_Higgs_DR_Higgs0PID':['AK4GEN_AllResolved_Higgs_DR_Higgs0PID', '#Delta R(AK4 higgs, higgs1 PID)', '', 25, 0, 7],
'AK4GEN_AllResolved_Higgs_DR_Higgs1PID':['AK4GEN_AllResolved_Higgs_DR_Higgs1PID', '#Delta R(AK4 higgs, higgs2 PID)', '', 25, 0, 7],


}